### ISSUE TITLE
Gene ID covert

### ISSUE THREAD

**Issue by Lyang556** [Tong-Chen/IMP#1]
Hi, 

The IMP is a  wonderful tool.

I'm using the GO & KEGG enrichment functions list in IMP.

The gene id of rice (Oryza sativa) does not start with LOC_Os or Os_ (MSU7.0 or RAPDB), could you please develop a tool that could covert these gene ids to the IMP* or allow these gene ids to conduct analysis.

Thank you.

**Comment by Tong-Chen** [comment]
Thanks! We would update the ids for model plants.

**Comment by Tong-Chen** [comment]
The gene id of rice (Oryza sativa) is corrected with LOC_Os ids. Please check. Thanks for the feedback. @Lyang556

**Comment by Lyang556** [comment]
@Tong-Chen  Thank you very much, i'll close this issue.
